package com.bankflow.transactionservice.pacs;

import java.util.Arrays;
import java.util.Optional;

/**
 * ISO 20022 status reason codes, as documented for KIPS.
 *
 * Descriptions are taken from the KIPS ACH message format specification rather
 * than the generic ISO list, so a rejection we send says what the scheme's own
 * documentation says it means.
 */
public enum ReasonCode {

    // --- account problems ---

    AC01("Incorrect account number"),
    AC04("Account number closed"),
    AC06("Locked account"),

    // --- amount and funds ---

    AM01("The total amount of the batch is zero"),
    AM02("The item has an invalid amount"),
    AM03("The item currency is not supported in the system"),
    AM04("Insufficient funds"),
    AM05("Duplicate"),

    // --- agent and routing ---

    AG01("Transaction prohibited"),
    AG02("Invalid banking operation code"),
    RC01("Invalid bank identifier"),
    RC02("Invalid sender BIC"),
    RC03("The instructed BIC is different from the ACH BIC"),

    // --- content ---

    RR01("Debtor identification account or missing"),
    RR02("Debtor's name or address missing"),
    RR03("Missing creditor name or address"),
    RR04("Regulatory reason"),
    BE05("Unrecognised initiating party"),
    FF01("General file format failure - the XML message fails schema validation"),
    FF05("Invalid local instrument code"),
    DT01("The specified settlement date is invalid"),

    // --- unspecified ---

    CUST("Item cancelled due to a customer request"),
    MS02("Unspecified reason generated by the client"),
    MS03("Unspecified reason generated by the agent"),
    NARR("Narrative - reason given in free text");

    private final String description;

    ReasonCode(String description) {
        this.description = description;
    }

    public String getCode() {
        return name();
    }

    public String getDescription() {
        return description;
    }

    public static Optional<ReasonCode> fromCode(String code) {

        return Arrays.stream(values())
                .filter(reason -> reason.name().equalsIgnoreCase(code))
                .findFirst();
    }
}
