/*
 * The banks this bank can pay.
 *
 * A BIC typed by hand is a BIC typed wrong eventually, and the payment that
 * carries it either fails schema validation or reaches the wrong institution.
 * Holding the list as data lets the form offer a choice instead.
 *
 * Entries are retired, never deleted: payments already sent quote the BIC, and
 * the directory has to keep explaining one that is no longer offered.
 */
CREATE TABLE IF NOT EXISTS correspondent_banks (

    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    bic        varchar(11)  NOT NULL UNIQUE,
    name       varchar(140) NOT NULL,
    country    varchar(2)   NOT NULL,
    active     boolean      NOT NULL DEFAULT true,

    created_at timestamp    NOT NULL,
    updated_at timestamp,

    /* ISO 9362: institution, country, location, and an optional branch. */
    CONSTRAINT ck_correspondent_bank_bic
        CHECK (bic ~ '^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$'),

    /* The country in the BIC and the country on the row are the same fact. */
    CONSTRAINT ck_correspondent_bank_country
        CHECK (country = SUBSTRING(bic FROM 5 FOR 2))
);

CREATE INDEX IF NOT EXISTS ix_correspondent_banks_active
    ON correspondent_banks (active);

/*
 * A starting set of Kosovo banks so the dropdown is not empty on a fresh
 * database. These are development seed values: check each against the CBK's
 * published register before relying on one, and correct it through the
 * directory screen rather than here.
 */
INSERT INTO correspondent_banks (bic, name, country, active, created_at)
VALUES
    ('TEBKXKPR', 'TEB Sh.A.',                         'XK', true, NOW()),
    ('RBKOXKPR', 'Raiffeisen Bank Kosovo J.S.C.',     'XK', true, NOW()),
    ('NCBAXKPR', 'Banka Kombetare Tregtare Kosove',   'XK', true, NOW()),
    ('MBKOXKPR', 'ProCredit Bank Kosovo',             'XK', true, NOW()),
    ('BPBAXKPR', 'Banka per Biznes',                  'XK', true, NOW()),
    ('EKOSXKPR', 'Banka Ekonomike',                   'XK', true, NOW()),
    ('NLPRXKPR', 'NLB Banka Prishtina',               'XK', true, NOW()),
    ('TCZBXKPR', 'Ziraat Bank Kosovo',                'XK', true, NOW()),
    ('CBRKXKPA', 'Central Bank of the Republic of Kosovo', 'XK', true, NOW())
ON CONFLICT (bic) DO NOTHING;
