/*
 * Days that have been closed.
 *
 * Closing is a decision recorded, not a calculation repeated. These are the
 * figures as at the moment somebody signed the day off, and they stay whatever
 * the ledger does afterwards — recomputing later answers what the books say
 * now, where an audit needs to know what they said then, and who accepted it.
 *
 * A closed day is sealed: nothing may be booked into it and it cannot be
 * closed twice. The unique booking date is what enforces the second half.
 */
CREATE TABLE IF NOT EXISTS day_closes (

    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    booking_date       date         NOT NULL UNIQUE,

    closed_by_username varchar(100) NOT NULL,
    closed_at          timestamp    NOT NULL,

    /* A day only seals when both proofs passed. */
    balanced           boolean      NOT NULL,
    reconciled         boolean      NOT NULL,

    entry_count        bigint       NOT NULL,
    total_debits       numeric(19,2) NOT NULL,
    total_credits      numeric(19,2) NOT NULL,
    matched_movements  integer      NOT NULL,

    /* What the person closing was told, kept verbatim. */
    summary            varchar(500) NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_day_closes_date
    ON day_closes (booking_date DESC);
