-- Baseline for transaction-service.
--
-- Represents the schema as it stood when Flyway was adopted. Existing
-- databases are baselined at version 1 and skip this file; a fresh database
-- runs it to create the schema from scratch.
--
-- Owns: transactions, ledger_entries, fee_rules, audit_events.
--
-- Note that account IDs are stored as plain bigints with no foreign key.
-- Accounts belong to account-service, and a database-level reference across a
-- service boundary would prevent ever splitting the schema.

CREATE TABLE IF NOT EXISTS transactions (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_reference  varchar(40)   NOT NULL,
    end_to_end_id          varchar(50),
    instruction_id         varchar(50)   NOT NULL,

    transaction_type       varchar(20)   NOT NULL,
    payment_type           varchar(30)   NOT NULL,
    direction              varchar(10)   NOT NULL,
    service_level          varchar(10),
    charge_bearer          varchar(10)   NOT NULL,
    purpose_code           varchar(10),
    status                 varchar(20)   NOT NULL,

    source_account_id      bigint        NOT NULL,
    -- Null for outbound payments: an external creditor has an IBAN, not a row.
    destination_account_id bigint,

    amount                 numeric(19,2) NOT NULL,
    currency               varchar(3)    NOT NULL,

    -- ISO 20022 party block, as carried by a pacs.008.
    debtor_name            varchar(140),
    debtor_iban            varchar(34),
    debtor_agent_bic       varchar(11),
    creditor_name          varchar(140),
    creditor_iban          varchar(34),
    creditor_agent_bic     varchar(11),
    remittance_information varchar(140),

    -- Charges. The money itself moves via a separate FEE transaction.
    fee_amount             numeric(19,2),
    debtor_fee_amount      numeric(19,2),
    creditor_fee_amount    numeric(19,2),
    parent_transaction_id  bigint,

    -- Four-eyes trail.
    created_by_user_id     bigint,
    created_by_username    varchar(50),
    approved_by_user_id    bigint,
    approved_by_username   varchar(50),
    approved_at            timestamp(6),
    rejection_reason       varchar(255),
    reason_code            varchar(10),

    booking_date           date          NOT NULL,
    value_date             date          NOT NULL,
    created_at             timestamp(6)  NOT NULL,
    updated_at             timestamp(6),

    CONSTRAINT uq_transactions_reference     UNIQUE (transaction_reference),
    CONSTRAINT uq_transactions_end_to_end_id UNIQUE (end_to_end_id),

    CONSTRAINT transactions_transaction_type_check
        CHECK (transaction_type IN
               ('TRANSFER', 'DEPOSIT', 'WITHDRAWAL', 'FEE', 'REVERSAL', 'RETURN')),

    CONSTRAINT transactions_payment_type_check
        CHECK (payment_type IN
               ('INTERNAL', 'SEPA_CREDIT_TRANSFER', 'SEPA_INSTANT', 'INTERNATIONAL')),

    CONSTRAINT transactions_direction_check
        CHECK (direction IN ('INTERNAL', 'OUTBOUND', 'INBOUND')),

    CONSTRAINT transactions_service_level_check
        CHECK (service_level IN ('SEPA', 'INST', 'URGP', 'SDVA', 'NURG')),

    CONSTRAINT transactions_charge_bearer_check
        CHECK (charge_bearer IN ('DEBT', 'CRED', 'SHAR', 'SLEV')),

    CONSTRAINT transactions_purpose_code_check
        CHECK (purpose_code IN
               ('SALA', 'PENS', 'SUPP', 'TAXS', 'RENT',
                'LOAN', 'INTC', 'TRAD', 'CASH', 'OTHR')),

    CONSTRAINT transactions_status_check
        CHECK (status IN
               ('PENDING', 'PENDING_APPROVAL', 'DECLINED', 'PROCESSING', 'SENT',
                'COMPLETED', 'SETTLED', 'REJECTED', 'RETURNED', 'FAILED')),

    CONSTRAINT transactions_currency_check
        CHECK (currency IN ('EUR', 'USD', 'GBP', 'CHF'))
);

CREATE INDEX IF NOT EXISTS idx_transaction_reference
    ON transactions (transaction_reference);

CREATE INDEX IF NOT EXISTS idx_end_to_end_id
    ON transactions (end_to_end_id);

CREATE TABLE IF NOT EXISTS ledger_entries (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id  bigint        NOT NULL,
    entry_reference varchar(40)   NOT NULL,
    account_id      bigint        NOT NULL,
    entry_type      varchar(10)   NOT NULL,
    amount          numeric(19,2) NOT NULL,
    currency        varchar(3)    NOT NULL,
    booking_date    date          NOT NULL,
    value_date      date          NOT NULL,
    created_at      timestamp(6)  NOT NULL,

    CONSTRAINT uq_ledger_entries_entry_reference UNIQUE (entry_reference),

    CONSTRAINT fk_ledger_entries_transaction
        FOREIGN KEY (transaction_id) REFERENCES transactions (id),

    CONSTRAINT ledger_entries_entry_type_check
        CHECK (entry_type IN ('DEBIT', 'CREDIT')),

    CONSTRAINT ledger_entries_currency_check
        CHECK (currency IN ('EUR', 'USD', 'GBP', 'CHF'))
);

CREATE INDEX IF NOT EXISTS idx_ledger_transaction_id
    ON ledger_entries (transaction_id);

CREATE INDEX IF NOT EXISTS idx_ledger_account_id
    ON ledger_entries (account_id);

CREATE INDEX IF NOT EXISTS idx_ledger_entry_reference
    ON ledger_entries (entry_reference);

CREATE INDEX IF NOT EXISTS idx_ledger_booking_date
    ON ledger_entries (booking_date);

-- The bank's tariff. Effective-dated rather than edited in place, so a
-- historic payment can be explained against the prices that were live.
CREATE TABLE IF NOT EXISTS fee_rules (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_code       varchar(50)   NOT NULL,
    description     varchar(140)  NOT NULL,
    payment_type    varchar(30)   NOT NULL,
    currency        varchar(3)    NOT NULL,
    min_amount      numeric(19,2) NOT NULL,
    max_amount      numeric(19,2),
    fixed_fee       numeric(19,2) NOT NULL,
    percentage_rate numeric(9,4)  NOT NULL,
    min_fee         numeric(19,2),
    max_fee         numeric(19,2),
    active          boolean       NOT NULL,
    valid_from      date          NOT NULL,
    valid_to        date,
    created_at      timestamp(6)  NOT NULL,

    CONSTRAINT uq_fee_rules_rule_code UNIQUE (rule_code),

    CONSTRAINT fee_rules_payment_type_check
        CHECK (payment_type IN
               ('INTERNAL', 'SEPA_CREDIT_TRANSFER', 'SEPA_INSTANT', 'INTERNATIONAL')),

    CONSTRAINT fee_rules_currency_check
        CHECK (currency IN ('EUR', 'USD', 'GBP', 'CHF'))
);

CREATE INDEX IF NOT EXISTS idx_fee_rule_lookup
    ON fee_rules (payment_type, currency, active);

-- Append-only business audit trail. Nothing in the application updates or
-- deletes these rows; an audit record that can be edited is not evidence.
CREATE TABLE IF NOT EXISTS audit_events (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type            varchar(40)  NOT NULL,
    transaction_reference varchar(40),
    entity_type           varchar(40)  NOT NULL,
    entity_id             varchar(50),
    actor_user_id         bigint,
    actor_username        varchar(50),
    actor_role            varchar(30),
    summary               varchar(500) NOT NULL,
    details               text,
    occurred_at           timestamp(6) NOT NULL,

    CONSTRAINT audit_events_event_type_check
        CHECK (event_type IN
               ('PAYMENT_INITIATED', 'PAYMENT_VALIDATED',
                'PAYMENT_SUBMITTED_FOR_APPROVAL', 'PAYMENT_APPROVED',
                'PAYMENT_DECLINED', 'FEE_ASSESSED', 'FEE_CHARGED',
                'ACCOUNT_DEBITED', 'ACCOUNT_CREDITED', 'LEDGER_ENTRY_POSTED',
                'PAYMENT_SENT', 'PAYMENT_SETTLED', 'PAYMENT_REJECTED',
                'PAYMENT_RETURNED', 'PAYMENT_FAILED', 'PAYMENT_REVERSED',
                'PACS_MESSAGE_GENERATED', 'PACS_MESSAGE_RECEIVED',
                'TARIFF_RULE_CREATED', 'TARIFF_RULE_CHANGED'))
);

CREATE INDEX IF NOT EXISTS idx_audit_transaction_reference
    ON audit_events (transaction_reference);

CREATE INDEX IF NOT EXISTS idx_audit_occurred_at
    ON audit_events (occurred_at);

CREATE INDEX IF NOT EXISTS idx_audit_event_type
    ON audit_events (event_type);

CREATE INDEX IF NOT EXISTS idx_audit_actor
    ON audit_events (actor_user_id);
