-- Realigns payment rails to the schemes a Kosovo bank actually reaches.
--
-- SEPA_CREDIT_TRANSFER and SEPA_INSTANT were placeholders; the real rails are
-- the two operated by the Central Bank of Kosovo (KIPS ACH for retail clearing,
-- KIPS RTGS for high-value gross settlement), plus correspondent banking for
-- payments leaving the country.
--
-- Also corrects two field sizes against the KIPS pacs.008 schema, where debtor
-- and creditor names are Max70Text rather than the 140 assumed earlier.

-- Order matters: the old constraints permit only the SEPA_* values, so they
-- have to come off before the data can be rewritten, and the new ones go on
-- afterwards once every row already satisfies them.
ALTER TABLE transactions DROP CONSTRAINT IF EXISTS transactions_payment_type_check;
ALTER TABLE fee_rules    DROP CONSTRAINT IF EXISTS fee_rules_payment_type_check;

UPDATE transactions
   SET payment_type = 'KIPS_ACH'
 WHERE payment_type = 'SEPA_CREDIT_TRANSFER';

UPDATE transactions
   SET payment_type = 'KIPS_RTGS'
 WHERE payment_type = 'SEPA_INSTANT';

UPDATE fee_rules
   SET payment_type = 'KIPS_ACH'
 WHERE payment_type = 'SEPA_CREDIT_TRANSFER';

UPDATE fee_rules
   SET payment_type = 'KIPS_RTGS'
 WHERE payment_type = 'SEPA_INSTANT';

-- The seeder installs the new tariff by rule code, so retire the old lines
-- rather than leaving them to compete for the same payment type.
UPDATE fee_rules
   SET active = false,
       valid_to = CURRENT_DATE
 WHERE rule_code IN ('TARIFF-SCT-EUR',
                     'TARIFF-SCTINST-EUR-LOW',
                     'TARIFF-SCTINST-EUR-HIGH');

ALTER TABLE transactions ADD CONSTRAINT transactions_payment_type_check
    CHECK (payment_type IN ('INTERNAL', 'KIPS_ACH', 'KIPS_RTGS', 'INTERNATIONAL'));

ALTER TABLE fee_rules ADD CONSTRAINT fee_rules_payment_type_check
    CHECK (payment_type IN ('INTERNAL', 'KIPS_ACH', 'KIPS_RTGS', 'INTERNATIONAL'));

-- KIPS ACH additionally restricts the service level to SEPA and RTGS uses URGP;
-- widen the permitted set rather than pin it, since the rail decides which
-- value applies and that rule lives in PaymentType.
ALTER TABLE transactions DROP CONSTRAINT IF EXISTS transactions_service_level_check;
ALTER TABLE transactions ADD CONSTRAINT transactions_service_level_check
    CHECK (service_level IN ('SEPA', 'INST', 'URGP', 'SDVA', 'NURG'));

-- Max70Text per the KIPS pacs.008 schema.
ALTER TABLE transactions ALTER COLUMN debtor_name   TYPE varchar(70);
ALTER TABLE transactions ALTER COLUMN creditor_name TYPE varchar(70);

-- Stored ISO 20022 messages. The raw XML is kept verbatim: a bank must be able
-- to show exactly what it sent or received, and reserialising from parsed
-- columns would produce something similar but not identical.
CREATE TABLE IF NOT EXISTS pacs_messages (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id            varchar(35)  NOT NULL,
    message_type          varchar(20)  NOT NULL,
    direction             varchar(10)  NOT NULL,
    status                varchar(20)  NOT NULL,
    transaction_reference varchar(40),
    end_to_end_id         varchar(50),
    related_message_id    varchar(35),
    status_code           varchar(10),
    reason_code           varchar(10),
    raw_xml               text         NOT NULL,
    created_at            timestamp(6) NOT NULL,

    CONSTRAINT uq_pacs_messages_message_id UNIQUE (message_id),

    CONSTRAINT pacs_messages_message_type_check
        CHECK (message_type IN ('PACS_008', 'PACS_002', 'PACS_004', 'PAIN_001')),

    CONSTRAINT pacs_messages_direction_check
        CHECK (direction IN ('OUTBOUND', 'INBOUND')),

    CONSTRAINT pacs_messages_status_check
        CHECK (status IN ('GENERATED', 'SENT', 'ACKNOWLEDGED', 'REJECTED', 'FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_pacs_transaction_reference
    ON pacs_messages (transaction_reference);

CREATE INDEX IF NOT EXISTS idx_pacs_message_type
    ON pacs_messages (message_type);

CREATE INDEX IF NOT EXISTS idx_pacs_created_at
    ON pacs_messages (created_at);

CREATE INDEX IF NOT EXISTS idx_pacs_related_message_id
    ON pacs_messages (related_message_id);
