/*
 * Recalls: asking for a settled payment back, and being asked.
 *
 * Held apart from the transaction because a recall is a conversation about a
 * payment rather than a state of it. It can be asked and refused, and the
 * payment is unchanged either way — only an accepted recall moves money, and
 * it does so through a return that books its own ledger entries.
 */
CREATE TABLE IF NOT EXISTS recall_requests (

    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    /* Our handle on the request, echoed as CxlId so an answer can be matched. */
    cancellation_id        VARCHAR(35)  NOT NULL UNIQUE,

    transaction_reference  VARCHAR(40)  NOT NULL,

    /* OUTBOUND: we are asking. INBOUND: we are being asked. */
    direction              VARCHAR(10)  NOT NULL,
    status                 VARCHAR(12)  NOT NULL,

    reason_code            VARCHAR(4)   NOT NULL,
    additional_information VARCHAR(105),

    requested_by_username  VARCHAR(100),
    decided_by_username    VARCHAR(100),
    decided_at             TIMESTAMP,
    decision_note          VARCHAR(255),

    created_at             TIMESTAMP    NOT NULL,

    CONSTRAINT ck_recall_direction
        CHECK (direction IN ('OUTBOUND', 'INBOUND')),

    CONSTRAINT ck_recall_status
        CHECK (status IN ('REQUESTED', 'ACCEPTED', 'REJECTED'))
);

CREATE INDEX IF NOT EXISTS ix_recall_requests_reference
    ON recall_requests (transaction_reference);

CREATE INDEX IF NOT EXISTS ix_recall_requests_status
    ON recall_requests (status);

/*
 * One unanswered request per payment. Two open claims on the same money is
 * not a state anybody could act on correctly.
 */
CREATE UNIQUE INDEX IF NOT EXISTS ux_recall_requests_open_per_payment
    ON recall_requests (transaction_reference)
    WHERE status = 'REQUESTED';
