-- Baseline for auth-service.
--
-- Represents the schema as it stood when Flyway was adopted. Existing
-- databases are baselined at version 1 and skip this file; a fresh database
-- runs it to create the schema from scratch.
--
-- auth-service owns only the users table. Other services' tables live in the
-- same schema but are owned by their own migrations.

CREATE TABLE IF NOT EXISTS users (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   varchar(50)  NOT NULL,
    email      varchar(150) NOT NULL,
    password   varchar(255) NOT NULL,
    role       varchar(30)  NOT NULL,
    status     varchar(20)  NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6),

    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email    UNIQUE (email),

    CONSTRAINT users_role_check
        CHECK (role IN ('BANK_ADMIN', 'OPERATIONS', 'TELLER', 'CUSTOMER')),

    CONSTRAINT users_status_check
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'LOCKED'))
);
