-- Baseline for account-service.
--
-- Represents the schema as it stood when Flyway was adopted. Existing
-- databases are baselined at version 1 and skip this file; a fresh database
-- runs it to create the schema from scratch.
--
-- Owns: clients (+ its JOINED subtype tables), accounts, balance_operations.

CREATE TABLE IF NOT EXISTS clients (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint       NOT NULL,
    client_type varchar(255) NOT NULL,
    email       varchar(255) NOT NULL,
    phone       varchar(255),
    status      varchar(255) NOT NULL,
    created_at  timestamp(6) NOT NULL,
    updated_at  timestamp(6),

    CONSTRAINT uq_clients_user_id UNIQUE (user_id),
    CONSTRAINT uq_clients_email   UNIQUE (email),

    CONSTRAINT clients_client_type_check
        CHECK (client_type IN ('INDIVIDUAL', 'BUSINESS'))
);

-- JOINED inheritance: one table per concrete client subtype.

CREATE TABLE IF NOT EXISTS individual_clients (
    client_id     bigint       NOT NULL PRIMARY KEY,
    first_name    varchar(255) NOT NULL,
    last_name     varchar(255) NOT NULL,
    date_of_birth date,

    CONSTRAINT fk_individual_clients_client
        FOREIGN KEY (client_id) REFERENCES clients (id)
);

CREATE TABLE IF NOT EXISTS business_clients (
    client_id           bigint       NOT NULL PRIMARY KEY,
    legal_name          varchar(255) NOT NULL,
    registration_number varchar(255) NOT NULL,
    tax_number          varchar(255),
    industry            varchar(255),

    CONSTRAINT uq_business_clients_registration_number
        UNIQUE (registration_number),

    CONSTRAINT fk_business_clients_client
        FOREIGN KEY (client_id) REFERENCES clients (id)
);

CREATE TABLE IF NOT EXISTS accounts (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id      bigint        NOT NULL,
    account_number varchar(16)   NOT NULL,
    iban           varchar(20)   NOT NULL,
    account_type   varchar(20)   NOT NULL,
    currency       varchar(3)    NOT NULL,
    balance        numeric(19,2) NOT NULL,
    status         varchar(20)   NOT NULL,
    created_at     timestamp(6)  NOT NULL,
    updated_at     timestamp(6),

    CONSTRAINT uq_accounts_account_number UNIQUE (account_number),
    CONSTRAINT uq_accounts_iban           UNIQUE (iban),

    CONSTRAINT fk_accounts_client
        FOREIGN KEY (client_id) REFERENCES clients (id),

    -- SUSPENSE and INCOME are the bank's own accounts, not customer products.
    CONSTRAINT accounts_account_type_check
        CHECK (account_type IN ('CURRENT', 'SAVINGS', 'SUSPENSE', 'INCOME')),

    CONSTRAINT accounts_currency_check
        CHECK (currency IN ('EUR', 'USD', 'GBP', 'CHF')),

    CONSTRAINT accounts_status_check
        CHECK (status IN ('ACTIVE', 'BLOCKED', 'CLOSED'))
);

-- Idempotency ledger for balance movements. The unique operation_id is what
-- makes a retried debit or credit safe to replay.
CREATE TABLE IF NOT EXISTS balance_operations (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id varchar(100)  NOT NULL,
    account_id   bigint        NOT NULL,
    operation    varchar(10)   NOT NULL,
    amount       numeric(19,2) NOT NULL,
    currency     varchar(3)    NOT NULL,
    created_at   timestamp(6)  NOT NULL,

    CONSTRAINT uq_balance_operations_operation_id UNIQUE (operation_id),

    CONSTRAINT balance_operations_operation_check
        CHECK (operation IN ('DEBIT', 'CREDIT')),

    CONSTRAINT balance_operations_currency_check
        CHECK (currency IN ('EUR', 'USD', 'GBP', 'CHF'))
);
