<?xml version="1.0" encoding="UTF-8"?>
<!-- Montran Corporation 2023.06. Last update: 2025.07.14 - LN -->
<xs:schema xmlns="urn:iso:std:iso:20022:tech:xsd:pacs.002.001.10"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="urn:iso:std:iso:20022:tech:xsd:pacs.002.001.10"
    elementFormDefault="qualified">
  <xs:element name="Document" type="Document"/>
  <xs:complexType name="Document">
     <xs:sequence>
       <xs:element name="FIToFIPmtStsRpt" type="FIToFIPaymentStatusReportV10"/>
     </xs:sequence>
  </xs:complexType>
  <xs:complexType name="FIToFIPaymentStatusReportV10">
     <xs:sequence>
       <xs:element name="GrpHdr" type="GroupHeader91"/>
       <xs:element name="OrgnlGrpInfAndSts" type="OriginalGroupHeader17"/>
       <xs:element name="TxInfAndSts" type="PaymentTransaction110" minOccurs="0" maxOccurs="unbounded"/>
     </xs:sequence>
  </xs:complexType>
  <xs:complexType name="GroupHeader91">
     <xs:sequence>
       <xs:element name="MsgId" type="Max35Text"/>
       <xs:element name="CreDtTm" type="ISODateTime"/>
       <xs:element name="InstgAgt" type="BranchAndFinancialInstitutionIdentification6" minOccurs="0"/>
       <xs:element name="InstdAgt" type="BranchAndFinancialInstitutionIdentification6" minOccurs="0"/>
     </xs:sequence>
  </xs:complexType>
  <xs:complexType name="OriginalGroupHeader17">
      <xs:sequence>
        <xs:element name="OrgnlMsgId" type="Max35Text"/>
        <xs:element name="OrgnlMsgNmId" type="Max35Text"/>
        <xs:element name="OrgnlNbOfTxs" type="Max15NumericText" minOccurs="0"/>
        <xs:element name="GrpSts" type="ExternalPaymentGroupStatus1Code" minOccurs="0"/>
        <xs:element name="StsRsnInf" type="StatusReasonInformation12" minOccurs="0"/>
        <xs:element name="NbOfTxsPerSts" type="NumberOfTransactionsPerStatus5" minOccurs="0" maxOccurs="unbounded"/> 
      </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PaymentTransaction110">
        <xs:sequence>
          <xs:element name="StsId" type="Max35Text"/>
          <xs:element name="OrgnlInstrId" type="Max35Text" minOccurs="0"/>
          <xs:element name="OrgnlEndToEndId" type="Max35Text"/>
          <xs:element name="OrgnlTxId" type="Max35Text"/>
          <xs:element name="TxSts" type="ExternalPaymentTransactionStatus1Code" minOccurs="0"/>
          <xs:element name="StsRsnInf" type="StatusReasonInformation12" minOccurs="0"/>
          <xs:element name="ChrgsInf" type="Charges7" minOccurs="0"/> 
          <xs:element name="InstgAgt" type="BranchAndFinancialInstitutionIdentification6" minOccurs="0"/>
          <xs:element name="InstdAgt" type="BranchAndFinancialInstitutionIdentification6" minOccurs="0"/>
          <xs:element name="OrgnlTxRef" type="OriginalTransactionReference28" minOccurs="0"/> 
        </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Charges7">
        <xs:sequence>
          <xs:element name="Amt" type="ActiveCurrencyAndAmount"/>
          <xs:element name="Agt" type="BranchAndFinancialInstitutionIdentification6"/>
        </xs:sequence>
  </xs:complexType>
  <xs:complexType name="OriginalTransactionReference28">
        <xs:sequence>
          <xs:element name="IntrBkSttlmAmt" type="ActiveCurrencyAndAmount" minOccurs="0"/>
          <xs:element name="IntrBkSttlmDt" type="ISODate" minOccurs="0"/>
          <xs:element name="SttlmInf" type="SettlementInstruction7" minOccurs="0"/>
          <xs:element name="PmtTpInf" type="PaymentTypeInformation27" minOccurs="0"/>
          <xs:element name="RmtInf" type="RemittanceInformation16" minOccurs="0"/>
          <xs:element name="UltmtDbtr" type="Party40Choice" minOccurs="0"/>
          <xs:element name="Dbtr" type="Party40Choice_2" minOccurs="0"/>
          <xs:element name="DbtrAcct" type="CashAccount38_2" minOccurs="0"/>
          <xs:element name="DbtrAgt" type="BranchAndFinancialInstitutionIdentification6" minOccurs="0"/>
          <xs:element name="CdtrAgt" type="BranchAndFinancialInstitutionIdentification6" minOccurs="0"/>
          <xs:element name="Cdtr" type="Party40Choice_2" minOccurs="0"/>
          <xs:element name="CdtrAcct" type="CashAccount38_2" minOccurs="0"/>
          <xs:element name="UltmtCdtr" type="Party40Choice" minOccurs="0"/>
          <xs:element name="Purp" type="Purpose2Choice" minOccurs="0"/>
        </xs:sequence>
  </xs:complexType>
  <xs:complexType name="BranchAndFinancialInstitutionIdentification6">
     <xs:sequence>
       <xs:element name="FinInstnId" type="FinancialInstitutionIdentification18"/>
     </xs:sequence>
  </xs:complexType>
  <xs:complexType name="FinancialInstitutionIdentification18">
      <xs:sequence>
        <xs:element name="BICFI" type="BICFIDec2014Identifier"/>
      </xs:sequence>
  </xs:complexType>
  <xs:complexType name="AccountIdentification4Choice">
    <xs:choice>
      <xs:element name="IBAN" type="IBAN2007Identifier"/>
      <xs:element name="Othr" type="GenericAccountIdentification1"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="AccountIdentification4Choice_2">
        <xs:choice>
          <xs:element name="IBAN" type="IBAN2007Identifier"/>
        </xs:choice>
  </xs:complexType>
  <xs:complexType name="AccountSchemeName1Choice">
    <xs:choice>
      <xs:element name="Cd" type="ExternalAccountIdentification1Code"/>
      <xs:element name="Prtry" type="Max35Text"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="ActiveCurrencyAndAmount">
        <xs:simpleContent>
            <xs:extension base="ActiveCurrencyAndAmount_SimpleType">
                <xs:attribute name="Ccy" type="ActiveCurrencyCode" use="required"/>
            </xs:extension>
        </xs:simpleContent>
   </xs:complexType>    
<xs:simpleType name="ActiveCurrencyAndAmount_SimpleType">
       <xs:restriction base="xs:decimal">
           <xs:minInclusive value="0.00"/>
           <xs:fractionDigits value="2"/>
           <xs:totalDigits value="17"/>
           <xs:maxInclusive value="999999999999999.99"/>
           <xs:pattern value="[0-9]{0,15}([\.]([0-9]{0,2})){0,1}"/>
       </xs:restriction>
   </xs:simpleType>
   <xs:simpleType name="ActiveCurrencyCode">
       <xs:restriction base="xs:string">
       	<xs:enumeration value="EUR"/>
       	<xs:enumeration value="ALL"/>
       </xs:restriction>
   </xs:simpleType>
  <xs:simpleType name="AnyBICDec2014Identifier">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z0-9]{4,4}[A-Z]{2,2}[A-Z0-9]{2,2}([A-Z0-9]{3,3}){0,1}"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="BICFIDec2014Identifier">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z0-9]{4,4}[A-Z]{2,2}[A-Z0-9]{2,2}([A-Z0-9]{3,3}){0,1}"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="CashAccount38">
        <xs:sequence>
          <xs:element name="Id" type="AccountIdentification4Choice"/>
        </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CashAccount38_2">
        <xs:sequence>
          <xs:element name="Id" type="AccountIdentification4Choice_2"/>
          <xs:element name="Prxy" type="ProxyAccountIdentification1" minOccurs="0"/>
        </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CategoryPurpose1Choice">
    <xs:choice>
      <xs:element name="Cd" type="ExternalCategoryPurpose1Code"/>
      <xs:element name="Prtry" type="Max35Text"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="ClearingSystemIdentification3Choice">
    <xs:choice>
      <xs:element name="Cd" type="ExternalCashClearingSystem1Code"/>
      <xs:element name="Prtry" type="Max35Text"/>
    </xs:choice>
  </xs:complexType>
  <xs:simpleType name="CountryCode">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{2,2}"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="CreditorReferenceInformation2">
        <xs:sequence>
          <xs:element name="Tp" type="CreditorReferenceType2"/>
          <xs:element name="Ref" type="Max35Text"/>
        </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CreditorReferenceType1Choice">
    <xs:choice>
      <xs:element name="Cd" type="DocumentType3Code"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="CreditorReferenceType2">
    <xs:sequence>
      <xs:element name="CdOrPrtry" type="CreditorReferenceType1Choice"/>
      <xs:element name="Issr" type="Max35Text" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="DateAndPlaceOfBirth1">
    <xs:sequence>
      <xs:element name="BirthDt" type="ISODate"/>
      <xs:element name="PrvcOfBirth" type="Max35Text" minOccurs="0"/>
      <xs:element name="CityOfBirth" type="Max35Text"/>
      <xs:element name="CtryOfBirth" type="CountryCode"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="DocumentType3Code">
    <xs:restriction base="xs:string">
      <xs:enumeration value="SCOR"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ExternalAccountIdentification1Code">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="4"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ExternalCashClearingSystem1Code">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="3"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ExternalCategoryPurpose1Code">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="4"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ExternalLocalInstrument1Code">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="35"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ExternalOrganisationIdentification1Code">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="4"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ExternalPaymentGroupStatus1Code">
  	<xs:restriction base="xs:string">
  		<xs:enumeration value="ACCP"/>
    	<xs:enumeration value="ACSC"/>
    	<xs:enumeration value="PART"/>
    	<xs:enumeration value="RJCT"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ExternalPaymentTransactionStatus1Code">
    <xs:restriction base="xs:string">
   		<xs:enumeration value="CLRD"/>
    	<xs:enumeration value="ACCP"/>
    	<xs:enumeration value="ACSC"/>
    	<xs:enumeration value="RJCT"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ExternalPersonIdentification1Code">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="4"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ExternalProxyAccountType1Code">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="4"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ExternalPurpose1Code">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="4"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ExternalServiceLevel1Code">
    <xs:restriction base="xs:string">
      <xs:enumeration value="SEPA"/>      
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ExternalStatusReason1Code">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="4"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="GenericAccountIdentification1">
    <xs:sequence>
      <xs:element name="Id" type="Max34Text"/>
      <xs:element name="SchmeNm" type="AccountSchemeName1Choice" minOccurs="0"/>
      <xs:element name="Issr" type="Max35Text" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="GenericOrganisationIdentification1">
    <xs:sequence>
      <xs:element name="Id" type="Max35Text"/>
      <xs:element name="SchmeNm" type="OrganisationIdentificationSchemeName1Choice" minOccurs="0"/>
      <xs:element name="Issr" type="Max35Text" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="GenericPersonIdentification1">
    <xs:sequence>
      <xs:element name="Id" type="Max35Text"/>
      <xs:element name="SchmeNm" type="PersonIdentificationSchemeName1Choice" minOccurs="0"/>
      <xs:element name="Issr" type="Max35Text" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="IBAN2007Identifier">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{2,2}[0-9]{2,2}[a-zA-Z0-9]{1,30}"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ISODate">
    <xs:restriction base="xs:date"/>
  </xs:simpleType>
  <xs:simpleType name="ISODateTime">
    <xs:restriction base="xs:dateTime"/>
  </xs:simpleType>
  <xs:simpleType name="LEIIdentifier">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z0-9]{18,18}[0-9]{2,2}"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="LocalInstrument2Choice">
    <xs:choice>
      <xs:element name="Cd" type="ExternalLocalInstrument1Code"/>
      <xs:element name="Prtry" type="Max35Text"/>
    </xs:choice>
  </xs:complexType>
  <xs:simpleType name="Max140Text">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="140"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Max16Text">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="16"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Max320Text">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="320"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Max34Text">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="34"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Max35Text">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="35"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Max70Text">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="70"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="OrganisationIdentification29">
        <xs:sequence>
          <xs:element name="AnyBIC" type="AnyBICDec2014Identifier"/>
        </xs:sequence>
  </xs:complexType>
  <xs:complexType name="OrganisationIdentification29_2">
        <xs:choice>
          <xs:element name="AnyBIC" type="AnyBICDec2014Identifier"/>
          <xs:element name="LEI" type="LEIIdentifier"/>
          <xs:element name="Othr" type="GenericOrganisationIdentification1"/>
        </xs:choice>
  </xs:complexType>
  <xs:complexType name="OrganisationIdentificationSchemeName1Choice">
    <xs:choice>
      <xs:element name="Cd" type="ExternalOrganisationIdentification1Code"/>
      <xs:element name="Prtry" type="Max35Text"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="Party38Choice">
        <xs:choice>
          <xs:element name="OrgId" type="OrganisationIdentification29"/>
        </xs:choice>
  </xs:complexType>
  <xs:complexType name="Party38Choice_2">
        <xs:choice>
          <xs:element name="OrgId" type="OrganisationIdentification29_2"/>
          <xs:element name="PrvtId" type="PersonIdentification13"/>
        </xs:choice>
  </xs:complexType>
  <xs:complexType name="Party40Choice">
        <xs:choice>
          <xs:element name="Pty" type="PartyIdentification135_2"/>
        </xs:choice>
  </xs:complexType>
  <xs:complexType name="Party40Choice_2">
        <xs:choice>
          <xs:element name="Pty" type="PartyIdentification135_3"/>
        </xs:choice>
  </xs:complexType>
  <xs:complexType name="PartyIdentification135">
        <xs:choice>
          <xs:element name="Nm" type="Max70Text"/>
          <xs:element name="Id" type="Party38Choice"/>
        </xs:choice>
  </xs:complexType>
  <xs:complexType name="PartyIdentification135_2">
        <xs:sequence>
          <xs:element name="Nm" type="Max70Text" minOccurs="0"/>
          <xs:element name="Id" type="Party38Choice_2" minOccurs="0"/>
        </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PartyIdentification135_3">
        <xs:sequence>
          <xs:element name="Nm" type="Max70Text"/>
          <xs:element name="PstlAdr" type="PostalAddress24" minOccurs="0"/>
          <xs:element name="Id" type="Party38Choice_2" minOccurs="0"/>
        </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PaymentTypeInformation27">
        <xs:sequence>
          <xs:element name="SvcLvl" type="ServiceLevel8Choice"  minOccurs="0"/>
          <xs:element name="LclInstrm" type="LocalInstrument2Choice" minOccurs="0"/>
          <xs:element name="CtgyPurp" type="CategoryPurpose1Choice" minOccurs="0"/>
        </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PersonIdentification13">
        <xs:choice>
          <xs:element name="DtAndPlcOfBirth" type="DateAndPlaceOfBirth1"/>
          <xs:element name="Othr" type="GenericPersonIdentification1"/>
        </xs:choice>
  </xs:complexType>
  <xs:complexType name="PersonIdentificationSchemeName1Choice">
    <xs:choice>
      <xs:element name="Cd" type="ExternalPersonIdentification1Code"/>
      <xs:element name="Prtry" type="Max35Text"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="PostalAddress24">
        <xs:sequence>
          <xs:element name="Dept" type="Max70Text" minOccurs="0"/>
          <xs:element name="SubDept" type="Max70Text" minOccurs="0"/>
          <xs:element name="StrtNm" type="Max70Text" minOccurs="0"/>
          <xs:element name="BldgNb" type="Max16Text" minOccurs="0"/>
          <xs:element name="BldgNm" type="Max35Text" minOccurs="0"/>
          <xs:element name="Flr" type="Max70Text" minOccurs="0"/>
          <xs:element name="PstBx" type="Max16Text" minOccurs="0"/>
          <xs:element name="Room" type="Max70Text" minOccurs="0"/>
          <xs:element name="PstCd" type="Max16Text" minOccurs="0"/>
          <xs:element name="TwnNm" type="Max35Text" minOccurs="0"/>
          <xs:element name="TwnLctnNm" type="Max35Text" minOccurs="0"/>
          <xs:element name="DstrctNm" type="Max35Text" minOccurs="0"/>
          <xs:element name="CtrySubDvsn" type="Max35Text" minOccurs="0"/>
          <xs:element name="Ctry" type="CountryCode" minOccurs="0"/>
          <xs:element name="AdrLine" type="Max70Text" minOccurs="0" maxOccurs="2"/>
        </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ProxyAccountIdentification1">
    <xs:sequence>
      <xs:element name="Tp" type="ProxyAccountType1Choice" minOccurs="0"/>
      <xs:element name="Id" type="Max320Text"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ProxyAccountType1Choice">
    <xs:choice>
      <xs:element name="Cd" type="ExternalProxyAccountType1Code"/>
      <xs:element name="Prtry" type="Max35Text"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="Purpose2Choice">
    <xs:choice>
      <xs:element name="Cd" type="ExternalPurpose1Code"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="RemittanceInformation16">
        <xs:sequence>
          <xs:element name="Ustrd" type="Max140Text" minOccurs="0"/>
          <xs:element name="Strd" type="StructuredRemittanceInformation16" minOccurs="0"/>
        </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ServiceLevel8Choice">
        <xs:choice>
          <xs:element name="Cd" type="ExternalServiceLevel1Code"/>
        </xs:choice>
  </xs:complexType>  
  <xs:complexType name="SettlementInstruction7">
        <xs:sequence>
          <xs:element name="SttlmMtd" type="SettlementMethod1Code"/>
          <xs:element name="SttlmAcct" type="CashAccount38" minOccurs="0"/>
          <xs:element name="ClrSys" type="ClearingSystemIdentification3Choice" minOccurs="0"/>
        </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="SettlementMethod1Code">
    <xs:restriction base="xs:string">
      <xs:enumeration value="CLRG"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="StatusReason6Choice">
        <xs:choice>
          <xs:element name="Cd" type="ExternalStatusReason1Code"/>
        </xs:choice>
  </xs:complexType>
  <xs:complexType name="StatusReasonInformation12">
        <xs:sequence>
          <xs:element name="Orgtr" type="PartyIdentification135"/>
          <xs:element name="Rsn" type="StatusReason6Choice" minOccurs="0"/>
          <xs:element name="AddtlInf" type="Max105Text" minOccurs="0" maxOccurs="unbounded"/>   
        </xs:sequence>
  </xs:complexType>
  <xs:complexType name="NumberOfTransactionsPerStatus5">
        <xs:sequence>
            <xs:element name="DtldNbOfTxs" type="Max15NumericText"/>
            <xs:element name="DtldSts" type="ExternalPaymentTransactionStatus1Code"/>
            <xs:element name="DtldCtrlSum" type="DecimalNumber" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
  <xs:complexType name="StructuredRemittanceInformation16">
        <xs:sequence>
          <xs:element name="CdtrRefInf" type="CreditorReferenceInformation2" minOccurs="0"/>
        </xs:sequence>
  </xs:complexType>
    <xs:simpleType name="Max15NumericText">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{1,15}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="DecimalNumber">
        <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="17"/>
            <xs:totalDigits value="18"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Max105Text">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="105"/>
        </xs:restriction>
    </xs:simpleType>       
</xs:schema>
